const shoes = [
  {
    id: 1,
    image: require("../src/static/shoes/shoe - 1.jpg"),
    productName: "Classic Sneakers",
    productPrice: "$50",
    color1: "White",
    color2: "Black",
    stockAvailable: true,
    gender: "men",
    size: "7",
  },
  {
    id: 2,
    image: require("../src/static/shoes/shoe - 2.jpg"),
    productName: "Running Shoes",
    productPrice: "$80",
    color1: "Blue",
    color2: "Red",
    stockAvailable: true,
    size: "8",
  },
  {
    id: 3,
    image: require("../src/static/shoes/shoe - 3.jpg"),
    productName: "High Heels",
    productPrice: "$100",
    color1: "Pink",
    color2: "Black",
    stockAvailable: true,
    size: "10",
  },
  {
    id: 4,
    image: require("../src/static/shoes/shoe - 4.jpg"),
    productName: "Casual Sandals",
    productPrice: "$40",
    color1: "Brown",
    color2: "Beige",
    stockAvailable: true,
    size: "9",
  },
  {
    id: 5,
    image: require("../src/static/shoes/shoe - 5.jpg"),
    productName: "Sports Shoes",
    productPrice: "$70",
    color1: "Green",
    color2: "Gray",
    stockAvailable: false,
    size: "9",
  },
  {
    id: 6,
    image: require("../src/static/shoes/shoe - 6.jpg"),
    productName: "Sports Shoes",
    productPrice: "$70",
    color1: "Green",
    color2: "Gray",
    stockAvailable: false,
    size: "9",
  },
  {
    id: 7,
    image: require("../src/static/shoes/shoe - 7.jpg"),
    productName: "Sports Shoes",
    productPrice: "$70",
    color1: "Green",
    color2: "Gray",
    stockAvailable: false,
    size: "9",
  },
  {
    id: 8,
    image: require("../src/static/shoes/shoe - 8.jpg"),
    productName: "Sports Shoes",
    productPrice: "$70",
    color1: "Green",
    color2: "Gray",
    stockAvailable: false,
    size: "9",
  },

  {
    id: 9,
    image: require("../src/static/shoes/shoe - 9.jpg"),
    productName: "Sports Shoes",
    productPrice: "$70",
    color1: "Green",
    color2: "Gray",
    stockAvailable: false,
    size: "9",
  },

  {
    id: 10,
    image: require("../src/static/shoes/shoe - 10.jpg"),
    productName: "Sports Shoes",
    productPrice: "$70",
    color1: "Green",
    color2: "Gray",
    stockAvailable: false,
    size: "9",
  },

  {
    id: 11,
    image: require("../src/static/shoes/shoe - 11.jpeg"),
    productName: "Running Shoes",
    productPrice: "$80",
    color1: "Blue",
    color2: "White",
    stockAvailable: true,
    size: "9",
  },
  {
    id: 12,
    image: require("../src/static/shoes/shoe - 12.jpg"),
    productName: "Casual Shoes",
    productPrice: "$60",
    color1: "Brown",
    color2: "Beige",
    stockAvailable: true,
    size: "9",
  },
];

export default shoes;
